apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy-replicas
  labels:
    kind: deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      # selector.matchLabels should be equal to template.metadata.labels
      app: myapp-replicas
  template:
    metadata:
      labels:
        # selector.matchLabels should be equal to template.metadata.labels
        app: myapp-replicas
        kind: pod
    spec:
      containers:
        - name: myapp-replicas-container
          # image can be changed without deleting pod
          image: k8s.gcr.io/echoserver:1.4
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    kind: service
spec:
  selector:
    app: myapp-replicas # labels of needed pods
  ports:
    - port: 3000 # load balancer port
      targetPort: 8080 # pod port
      name: myapp-listener
      protocol: TCP
  type: LoadBalancer
